parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\UI\Command\:
        resource: '../src/UI/Command'
        autoconfigure: true
        bind:
            $messageBus: '@messenger.default_bus'


    App\CommandHandler\:
        resource: '%kernel.project_dir%/src/CommandHandler/*'
        tags:
            - { name: messenger.message_handler }
        bind:
            $messageBus: '@messenger.default_bus'


    App\Saga\:
        resource: '%kernel.project_dir%/src/Saga/*'
        tags:
            - { name: messenger.message_handler }
        bind:
            $messageBus: '@messenger.default_bus'
            $stateRepository: '@app.saga.state_repository'

    app.saga.state_repository:
         class: 'App\ProcessManager\InMemoryStateRepository'
