parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\SfCommand\:
        resource: '../src/SfCommand'
        bind:
            $messageBus: '@messenger.default_bus'


    App\CommandHandler\:
        resource: '%kernel.project_dir%/src/CommandHandler/*'
        tags:
            - { name: messenger.message_handler }
        bind:
            $messageBus: '@messenger.default_bus'


    App\Saga\:
        resource: '%kernel.project_dir%/src/Saga/*'
        tags:
            - { name: messenger.message_handler }
        bind:
            $messageBus: '@messenger.default_bus'
            $stateRepository: '@app.saga.state_repository'

    app.saga.state_repository:
         class: 'App\ProcessManager\InMemoryStateRepository'
